config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  # Protect against timing attacks:
  # - See https://codahale.com/a-lesson-in-timing-attacks/
  # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
  # - Use & (do not use &&) so that it doesn't short circuit.
  # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
  ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
end if Rails.env.production?

Rails.application.routes.draw do
  post "/graphql", to: "graphql#execute"
  root 'sessions#new'

  get 'sessions/destroy'

  resources :sessions, only: [ :new, :create ]
  namespace :admin do
    resources :companies do
      resources :billing_details, only: [ :new, :create ], controller: 'companies/billing_details'
      resources :video_play_logs, only: [ :new, :create ], controller: 'companies/video_play_logs'
      resources :credits, only: [ :index, :new, :create ], controller: 'companies/credits'
      resources :channels, only: [ :index ], controller: 'companies/channels'
      resources :channel_playlists, only: [ :index ], controller: 'companies/channel_playlists'
    end
    resources :users
    resources :videos do
      member do
        post 'approve'
        post 'reject'
      end
    end
  end

  namespace :fleet do
    namespace :admin do
      resources :videos, only: [ :index ] do
        resources :approvals, only: [ :create ], controller: 'videos/approvals'
        resources :rejections, only: [ :create ], controller: 'videos/rejections'
      end
    end
    resources :channels, only: [ :index ]
    resources :channel_playlists, only: [ :index ]
    resources :channel_playlist_assignments
    resources :vessels
    resources :vessel_route_schedules, only: %i[ index create ] do
      collection do
        post 'new_schedule'
      end

      member do
        post 'activate'
        post 'deactivate'
      end
    end
    resources :vessel_routes, except: %i[destroy]
    resources :vessel_schedules, only: [ :index, :show ]
    resources :vessel_waypoints, only: [ :new ]
    resources :playlist_assignments, only: %i[ new create ]
    resources :playlists do
      member do
        post 'set_default'
      end
    end
    resources :onboarding_playlist, controller: 'playlists'
    resources :offboarding_playlist, controller: 'playlists'
    resources :videos
    resources :playlist_videos do
      member do
        post 'set_play_order'
      end
    end

    get 'vessel_media_settings/edit/:vessel_id/:route_id',
      to: 'vessel_media_settings#edit', as: :edit_vessel_media_settings

    post 'save/:id',
      to: 'vessel_media_settings#save', as: :save_vessel_media_settings
  end

  namespace :media do
    resources :campaigns do
      collection do
        post 'set_playlist'
      end
    end
    resources :playlists do
      member do
        post 'archive'
        post 'set_default'
      end
    end
    resources :spots do
      collection do
        post 'calculate'
      end
    end
    resources :videos
    resources :playlist_assignments
    resources :playlist_videos do
      member do
        post 'set_play_order'
      end
    end
  end

  namespace :content_provider do
    resources :videos
  end

  namespace :spots do
    resources :vehicle_route_schedules, only: [ ], controller: '/media/spots/vehicle_route_schedules' do
      collection do
        post 'search'
      end
    end
  end

  namespace :users do
    resource :password_reset, only: [ :new, :create ], controller: '/users/password_reset'
  end

  mount Sidekiq::Web => '/sidekiq'
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
end

app/controllers/fleet/admin/videos/approvals_controller.rb
# frozen_string_literal: true

class Fleet::Admin::Videos::ApprovalsController < ApplicationController
  before_action :set_video

  def create
    @video.approved!
    @video.broadcast_replace_to Current.user, 'fleet:admin:videos', partial: 'fleet/admin/videos/video'

    Current.company.vehicles.each { |vehicle|
      Vessel::NotifyDownloadVideosJob.perform_later(vehicle)
    }

    respond_to do |format|
      format.any { head :ok }
    end
  end

  private
    def set_video
      @video = Video.find(params[:video_id])
    end
end

app/controllers/fleet/admin/videos/rejections_controller.rb
# frozen_string_literal: true

class Fleet::Admin::Videos::RejectionsController < ApplicationController
  before_action :set_video

  def create
    @video.rejected!
    @video.broadcast_replace_to Current.user, 'fleet:admin:videos', partial: 'fleet/admin/videos/video'
    respond_to do |format|
      format.any { head :ok }
    end
  end

  private
    def set_video
      @video = Video.find(params[:video_id])
    end
end

app/controllers/fleet/admin/videos_controller.rb
# frozen_string_literal: true

class Fleet::Admin::VideosController < Fleet::BaseController
  before_action :set_videos, only: %w(index)

  def index
    respond_to do |format|
      format.html
      format.turbo_stream {
        render turbo_stream: turbo_stream.replace("list_videos", partial: 'videos')
      }
    end
  end

  private
    def set_videos
      @videos = Video.search(
        filters: {
          video_type: video_type,
          demo_or_skooteo: Current.company.demo?,
          sort: 'created_at desc'
        },
        page: params[:page] || 1,
        per_page: params[:per_page],
      )
    end

    def video_type
      params[:video_type] || Video.types.entertainment
    end
end

app/controllers/fleet/base_controller.rb
# frozen_string_literal: true

module Fleet
  class BaseController < ApplicationController
    before_action :require_fleet_operator!
  end
end

app/controllers/fleet/channel_playlists_controller.rb
# frozen_string_literal: true

module Fleet
  class ChannelPlaylistsController < BaseController
    before_action :set_playlists, only: %w(index)

    private
      def set_playlists
        @playlists = Current.company.playlists.active.
          where(channel: params[:channel]).order(:created_at)
        @channel = params[:channel]
      end
  end
end

app/controllers/fleet/channels_controller.rb
module Fleet
  class ChannelsController < BaseController
    before_action :set_channels

    private

    def set_channels
      @channels = Channels.new Current.company
    end
  end
end

app/controllers/fleet/playlist_assignments_controller.rb
# frozen_string_literal: true

module Fleet
  class PlaylistAssignmentsController < BaseController
    before_action :set_playlist, only: %w(new create)
    before_action :set_videos, only: %w(create)

    def new
      @videos = Video.selections(Current.company, @playlist)
      respond_to do |format|
        format.turbo_stream {
          render turbo_stream: turbo_stream.update('modal-container', partial: 'edit')
        }
        format.html {
          redirect_to fleet_playlists_path
        }
      end
    end

    def create
      @playlist.transaction do
        @videos.each { |video|
          @playlist.playlist_videos.find_or_create_by!(video: video, company: Current.company)
        }
      end

      @playlist.broadcast_replace_to Current.user, 'fleet:playlist_assignment', partial: playlist_partial, object: @playlist
      @playlist.broadcast_replace_to Current.user, 'fleet:playlist_assignment', partial: 'shared/modal', target: 'modal-container'

      respond_to do |format|
        format.any { head :ok }
      end
    end

    private
      def set_playlist
        @playlist = Current.company.playlists.find params[:playlist_id]
      end

      def set_videos
        @videos = Current.company.videos.where(id: video_params)
      end

      def video_params
        params.require(:video_ids)
      end

      def playlist_partial
        @playlist.channel.present? ? 'fleet/channel_playlists/playlist' :
          'fleet/playlists/playlist'
      end
  end
end

app/controllers/fleet/playlist_videos_controller.rb
# frozen_string_literal: true

module Fleet
  class PlaylistVideosController < BaseController
    skip_before_action :require_fleet_operator!, only: %w(destroy)
    before_action :set_playlist, except: %w(destroy)
    before_action :set_playlist_video, only: %w(set_play_order destroy)

    def destroy
      @playlist_video.destroy
      @playlist_video.broadcast_remove_to 'fleet:playlist'
      respond_to do |format|
        format.any { head :ok }
      end
    end

    def set_play_order
      @playlist.switch_playorder!(@playlist_video, params[:play_order].to_i)
      head :ok
    end

    private
      def set_playlist
        @playlist = Current.company.playlists.find params[:playlist_id]
      end

      def set_playlist_video
        @playlist_video = PlaylistVideo.find params[:id]
      end
  end
end

app/controllers/fleet/playlists_controller.rb
# frozen_string_literal: true

module Fleet
  class PlaylistsController < BaseController
    include Playlists::Admin

    protected
      def namespace
        @ns ||= 'fleet'
      end
  end
end

app/controllers/fleet/vessel_media_settings_controller.rb
# frozen_string_literal: true

module Fleet
  class VesselMediaSettingsController < BaseController
    before_action :set_route, only: %i[ edit ]
    before_action :set_vessel, only: %i[ edit ]
    before_action :set_vessel_route, only: %i[ save ]

    def edit
      VehicleRoute.ensure_unique_existence!(@vessel, @route)
      @vessel_route = Current.company.vehicle_routes.find_by(route: @route, vehicle: @vessel)
    end

    def save
      @vessel_route.update_from_params(route_params.to_h.deep_symbolize_keys)
    end

    private
      def route_params
        params
          .require(:vessel_route)
          .permit(
            ett: {}, onboarding: {}, offboarding: {},
            arrival_trigger: {}, regular_ads: {}, premium_ads: {},
            regular_ads_segment: {}, premium_ads_segment: {}
          )
      end

      def set_route
        @route = Current.company.routes.find(params[:route_id])
      end

      def set_vessel
        @vessel = Current.company.vessels.find(params[:vessel_id])
      end

      def set_vessel_route
        @vessel_route = Current.company.vehicle_routes.find(params[:id])
      end
  end
end

app/controllers/fleet/vessel_route_schedules_controller.rb
# frozen_string_literal: true

module Fleet
  class VesselRouteSchedulesController < ::Fleet::BaseController
    before_action :set_vessel, :set_route, except: %w(edit show activate deactivate)
    before_action :set_vessel_route, only: %w(new_schedule index create)
    before_action :set_vessel_schedule, only: %w(edit activate deactivate)

    def index
      @period = [
        params[:yyyy] || Date.today.year,
        (params[:mm] || Date.today.month).to_s.rjust(2, '0'),
        '01'
      ].join('-')
      @period = @period.to_date
      @vessel_schedules = VehicleRouteSchedule.results(filters: {
        vehicle_route: @vessel_route,
        inactive: params[:inactive],
        period: {
          mm: @period.month,
          yyyy: @period.year
        }
      })
    end

    def new_schedule
      @vessel_schedule = VehicleRouteSchedule.new
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(:new_schedule_template, partial: 'new')
        end
        format.html {
          redirect_to fleet_vessels_path
        }
      end
    end

    def create
      @vehicle_schedule_template = VehicleRouteSchedule::Template.new(vehicle_schedule_template)
      @vehicle_schedule_template.create_schedules!(@vessel_route)
      respond_to do |format|
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace(
            :new_schedule_template,
            %Q(<tr class="is-hidden" id="new_schedule_template" />)
          )
        end
      end
    end

    def activate
      if @vessel_schedule.inactive?
        # NOTE: when debugging the history of activation/deactivation
        # check the event's table
        @vessel_schedule.status_text = nil
        @vessel_schedule.active!
      end
      @vessel_schedule.broadcast_remove_to 'fleet:schedules'
      respond_to do |format|
        format.any do
          head :ok
        end
      end
    end

    def deactivate
      if @vessel_schedule.active?
        @vessel_schedule.status_text = params[:value]
        @vessel_schedule.inactive!
        # TODO: remove all spots and refund customer credits
      end
      @vessel_schedule.broadcast_remove_to 'fleet:schedules'
      respond_to do |format|
        format.any do
          head :ok
        end
      end
    end

    private
      def set_vessel
        @vessel = Current.company.vehicles.find(params[:vessel_id])
      end

      def set_route
        @route = Current.company.routes.find(params[:route_id])
      end

      def set_vessel_route
        @vessel_route = Current.company.vehicle_routes.find_by(
          vehicle_id: params[:vessel_id],
          route_id: params[:route_id]
        )
      end

      def set_vessel_schedule
        @vessel_schedule = VehicleRouteSchedule.unscoped.find params[:id]
        @route = @vessel_schedule.route
        @vessel = @vessel_schedule.vehicle
      end

      def vehicle_schedule_template
        params.require(:vehicle_schedule_template)
          .permit(:effective_start_date, :effective_end_date, :td, days: {})
      end
  end
end

app/controllers/fleet/vessel_routes_controller.rb
# frozen_string_literal: true

module Fleet
  class VesselRoutesController < BaseController
    skip_before_action :require_fleet_operator!, only: %w(index)

    before_action :set_vessel, except: %w(index)
    before_action :set_routes, only: %w(index)
    before_action :set_route, only: %w(edit update destroy)

    def index
      @route = @routes.results.first
      respond_to do |format|
        format.html do
          set_vessel
          render layout: false
        end
        format.json { render json: @routes.results }
      end
    end

    def new
      @route = Route.new
      render action: :edit
    end

    def edit
    end

    def create
      @route = Current.company.routes.create!(normalize_params)
      set_routes
    end

    def update
      @route.transaction do
        @route.waypoints.destroy_all
        @route.update!(normalize_params)
      end
    end

    private
      def set_routes
        @routes ||=
          Route.search(
            filters: {
               company_ids: get_company_scope,
               query: params[:q]
            },
            page: params[:page] || 1,
            per_page: params[:per_page] || 100
          )
      end

      def get_company_scope
        params[:company_ids] || Current.company.id
      end

      def set_vessel
        @vessel = Current.company.vehicles.find(params[:vessel_id])
      end

      def set_route
        @route = Current.company.routes.find params[:id]
      end

      def normalize_params
        route_attributes = route_params.to_h
        distances = route_attributes.extract!('distance_in_km', 'first_half_distance_in_km')
        hash = route_attributes.merge({
          'distance' => MetricDistance.from_km(distances['distance_in_km']),
          'first_half_distance' => MetricDistance.from_km(distances['first_half_distance_in_km'])
        })
      end

      def route_params
        params
          .require(:route)
          .permit(
            :name,
            :first_half_distance_in_km,
            :distance_in_km,
            waypoints_attributes: [:name, :sequence, :coordinates])
      end
  end
end

app/controllers/fleet/vessel_schedules_controller.rb
# frozen_string_literal: true

module Fleet
  class VesselSchedulesController < BaseController
    before_action :set_route
    before_action :set_schedules

    def index
    end

    private
      def set_route
        @route = params[:route_id].present? ? Current.company.routes.find(params[:route_id]) : nil
      end

      def set_schedules
        @period = [
          params.dig(:date, :year) || Date.today.year,
          (params.dig(:date, :month) || Date.today.month).to_s.rjust(2, '0'),
          '01'
        ].join('-')
        @period = @period.to_date
        @vessel_schedules = VehicleRouteSchedule.results(filters: {
          inactive: '0',
          route: @route,
          company_ids: [Current.company.id],
          period: {
            mm: @period.month,
            yyyy: @period.year
          }
        }).includes(:vehicle, :route).order('etd desc')
      end
  end
end

app/controllers/fleet/vessel_waypoints_controller.rb
# frozen_string_literal: true

module Fleet
  class VesselWaypointsController < BaseController
    def new
      @waypoint = Waypoint.new sequence: params[:pos].to_i,
        coordinates: params[:coord], name: "waypoint #{params[:pos]}"
      @waypoint.broadcast_append_to Current.user, 'fleet:routes', target: 'waypointset',
        partial: 'fleet/vessel_waypoints/waypoint', locals: { waypoint: @waypoint }
      head :ok
    end
  end
end

app/views/fleet/vessel_route_schedules/_new.html.erb
<tr class="is-highlighted" id="new_schedule_template" data-controller="toggle-element">
  <td colspan="4" style="padding: 0px">
    <%= form_with(model: @vessel_schedule, url: fleet_vessel_route_schedules_path, method: 'post') do |form| %>
      <%= hidden_field_tag :vessel_id, @vessel.id %>
      <%= hidden_field_tag :route_id, @route.id %>

      <table class="table is-fullwidth is-editable" id="route-schedule-form-container">
        <tbody>
          <tr class="is-highlighted">
            <td />
            <td />
            <td>
              <button type="submit" class="button is-primary">
                Save
              </button>
              <button
                class="button is-primary is-outlined"
                data-action="click->toggle-element#close"
              >Cancel</button>
            </td>
          </tr>
          <tr>
            <td class="is-form-label" colspan="1">Start date:</td>
            <td class="is-form-field-content" colspan="3">
              <%= date_field_tag "vehicle_schedule_template[effective_start_date]",
                1.day.since.to_date.iso8601,
                data: { controller: 'pikaday', action: 'change->pikaday#change' } %>
              <%= hidden_field_tag "vehicle_schedule_template[effective_end_date]",
                7.days.since.to_date.iso8601, data: {
                  controller: 'vehicle-schedule-end-date-field'
                } %>
            </td>
          </tr>
          <tr>
            <td class="is-form-label" colspan="1">End date:</td>
            <td class="is-form-field-content" colspan="5">
              <span id="vehicle_schedule_end_date_label">
                <%= 7.days.since.to_date.iso8601 %>
              </span>
            </td>
          </tr>
          <tr data-target="vessel-route-schedules.daysRow">
            <td class="is-form-label" colspan="1">Day:</td>
            <td class="is-form-field-content" colspan="3">
              <% options_for_wday.each do |(wday, i)| %>
                <label class="checkbox">
                  <%= wday[0..2] %>
                  <%= check_box_tag("vehicle_schedule_template[days][#{i}]", i, true, multiple: true) %>
                </label>
              <% end %>
            </td>
          </tr>
          <tr>
            <td class="is-form-label" colspan="1">Departure time:</td>
            <td class="is-form-field-content" colspan="3">
              <%= time_field_tag "vehicle_schedule_template[td]" %>
            </td>
          </tr>
          <tr>
            <td class="is-form-label" colspan="1">Travel time:</td>
            <td class="is-form-field-content" colspan="3">
              <div class="form-field-content is-bold">
                <%= @vessel_route.estimated_travel_duration.inspect %>,&nbsp;as per route settings
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    <% end %>
  </td>
</tr>

app/views/fleet/vessel_route_schedules/_schedule.html.erb
<tr class="schedule-row" id="<%= dom_id(schedule)%>">
  <td><%= l schedule.etd %></td>
  <td><%= l schedule.eta %></td>
  <td><%= h schedule.creator.email %></td>
  <td>
    <button
      data-controller="confirm-action"
      data-confirm-action-url-value="<%=deactivate_fleet_vessel_route_schedule_path(schedule)%>"
      data-confirm-action-method-value="POST"
      data-confirm-action-message-value="Reason"
      data-action="click->confirm-action#trigger"
      class="button is-primary <%= params[:inactive] == '1' ? 'is-hidden' : nil %>"
    >
      Cancel
    </button>
    <%= button_to "Restore", activate_fleet_vessel_route_schedule_path(schedule),
      class: "button is-info #{params[:inactive] != '1' ? 'is-hidden' : nil}" %>
  </td>
</tr>

app/views/fleet/vessel_route_schedules/index.html.erb
<turbo-frame id="edit_route">
  <%= turbo_stream_from 'fleet:schedules' %>
  <div class="column">
    <%= render "fleet/vessel_routes/tabs" %>
    <div class="columns">
      <div class="column">
        <div class="m-b-md">
          <% unless params[:inactive] == '1' %>
            <%= button_to new_schedule_fleet_vessel_route_schedules_path(route_id: @route.id, vessel_id: @vessel.id), class: 'button is-primary' do %>
              <span class="icon m-r-sm">
                <i class="fas fa-plus"></i>
              </span>
              Add Vessel Schedule
            <% end %>
          <% end %>
          <div
            class="schedule-filter is-pulled-right"
            data-controller="vessel-schedule-filters"
            data-basepath="<%=fleet_vessel_route_schedules_url(route_id: @route.id, vessel_id: @vessel.id)%>"
          >
            <div class="select">
              <%= select_month @period, {}, { 'data-vessel-schedule-filters-target': 'month' } %>
            </div>
            <div class="select">
              <%= select_year @period, {}, { 'data-vessel-schedule-filters-target': 'year' } %>
            </div>
            <div class="select">
              <%= select_tag 'status', options_for_schedule_statuses,
                'data-vessel-schedule-filters-target': "status" %>
            </div>
            <button class="button is-info is-outlined" data-action="click->vessel-schedule-filters#apply">
              Show
            </button>
          </div>
        </div>
        <table class="table is-fullwidth is-editable is-hoverable">
          <thead>
            <tr>
              <th>ETD</th>
              <th>ETA</th>
              <th>Creator</th>
              <th>Action</th>
            </tr>
          </thead>
          <tbody id="schedules">
            <!-- do not delete this, form for new schedule will be hosted in this element -->
            <tr class="is-hidden" id="new_schedule_template" />
            <%= render partial: 'schedule', collection: (@vessel_schedules) %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</turbo-frame>