config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  # Protect against timing attacks:
  # - See https://codahale.com/a-lesson-in-timing-attacks/
  # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
  # - Use & (do not use &&) so that it doesn't short circuit.
  # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
  ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
end if Rails.env.production?

Rails.application.routes.draw do
  post "/graphql", to: "graphql#execute"
  root 'sessions#new'

  get 'sessions/destroy'

  resources :sessions, only: [ :new, :create ]
  namespace :admin do
    resources :companies do
      resources :billing_details, only: [ :new, :create ], controller: 'companies/billing_details'
      resources :video_play_logs, only: [ :new, :create ], controller: 'companies/video_play_logs'
      resources :credits, only: [ :index, :new, :create ], controller: 'companies/credits'
      resources :channels, only: [ :index ], controller: 'companies/channels'
      resources :channel_playlists, only: [ :index ], controller: 'companies/channel_playlists'
    end
    resources :users
    resources :videos do
      member do
        post 'approve'
        post 'reject'
      end
    end
  end

  namespace :fleet do
    namespace :admin do
      resources :videos, only: [ :index ] do
        resources :approvals, only: [ :create ], controller: 'videos/approvals'
        resources :rejections, only: [ :create ], controller: 'videos/rejections'
      end
    end
    resources :channels, only: [ :index ]
    resources :channel_playlists, only: [ :index ]
    resources :channel_playlist_assignments
    resources :vessels
    resources :vessel_route_schedules, only: %i[ index create ] do
      collection do
        post 'new_schedule'
      end

      member do
        post 'activate'
        post 'deactivate'
      end
    end
    resources :vessel_routes, except: %i[destroy]
    resources :vessel_schedules, only: [ :index, :show ]
    resources :vessel_waypoints, only: [ :new ]
    resources :playlist_assignments, only: %i[ new create ]
    resources :playlists do
      member do
        post 'set_default'
      end
    end
    resources :onboarding_playlist, controller: 'playlists'
    resources :offboarding_playlist, controller: 'playlists'
    resources :videos
    resources :playlist_videos do
      member do
        post 'set_play_order'
      end
    end

    get 'vessel_media_settings/edit/:vessel_id/:route_id',
      to: 'vessel_media_settings#edit', as: :edit_vessel_media_settings

    post 'save/:id',
      to: 'vessel_media_settings#save', as: :save_vessel_media_settings
  end

  namespace :media do
    resources :campaigns do
      collection do
        post 'set_playlist'
      end
    end
    resources :playlists do
      member do
        post 'archive'
        post 'set_default'
      end
    end
    resources :spots do
      collection do
        post 'calculate'
      end
    end
    resources :videos
    resources :playlist_assignments
    resources :playlist_videos do
      member do
        post 'set_play_order'
      end
    end
  end

  namespace :content_provider do
    resources :videos
  end

  namespace :spots do
    resources :vehicle_route_schedules, only: [ ], controller: '/media/spots/vehicle_route_schedules' do
      collection do
        post 'search'
      end
    end
  end

  namespace :users do
    resource :password_reset, only: [ :new, :create ], controller: '/users/password_reset'
  end

  mount Sidekiq::Web => '/sidekiq'
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  include Confirmable
  include HasFinder

  has_many :videos, foreign_key: :creator_id

  has_one :person, inverse_of: :user
  has_one :user_role, inverse_of: :user
  has_one :role, through: :user_role

  has_secure_password

  belongs_to :company, touch: true, optional: true

  accepts_nested_attributes_for :person, :user_role

  validates :email, presence: true, uniqueness: true

  delegate :full_name, to: :person

  def self.create_nologin_account(company)
    company.users.create(
      email: "#{company.id}@system.skooteo.com",
      password: SecureRandom.hex(12),
      no_login: true
    )
  end
end

app/models/user/finder.rb
# frozen_string_literal: true

class User::Finder
  include SearchObject.module :will_paginate, :sorting

  scope {
    User.joins(:person).order('people.last_name, people.first_name')
  }

  option(:query) do |scope, query|
    where_string = "people.first_name ILIKE '%<query>s' OR " \
    "people.last_name ILIKE '%<query>s' OR " \
    "users.email ILIKE '%<query>s'".% [query: "%#{query}%"]

    (query && scope.where(where_string)) || scope
  end

  per_page 30
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

module Admin
  class UsersController < BaseController
    before_action :set_users, only: %w(index)
    before_action :set_user, only: %w(edit update)

    def new
      respond_to do |format|
        format.turbo_stream {
          render turbo_stream: turbo_stream.update("modal-container", partial: "edit")
        }
      end
    end

    def create
      @user = User.create!(user_params)
    end

    def update
      @user.update! user_params
    end

    private
      def set_users
        @users = User.search(
          page: params[:page] || 1,
          per_page: params[:per_page],
          filters: { query: params[:q] }
        )
      end

      def set_user
        @user = User.find params[:id]
      end

      def user_params
        params.require(:user).
          permit(
            :email,
            :password,
            :company_id,
            person_attributes: [:last_name, :first_name, :id],
            user_role_attributes: [:id, :grantor_id, :role_id]
          )
      end
  end
end

app/controllers/users/password_reset_controller.rb
module Users
  class PasswordResetController < ApplicationController
    def create
      begin
        if PasswordResetPolicy.can_reset_password?(Current.user, params)
          service = UserServices::PasswordReset.new(
            Current.user,
            params[:old_password],
            params[:new_password]
          )
          service.call
        else
          raise 'Password reset failed, make sure all fields are filled in and confirmation matches new password.'
        end
        flash[:notice] = 'Password updated!'
      rescue => e
        flash[:error] = e.message
      end
      render :new
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def company_options selected
    @options ||= (
      company_by_type = companies.group_by(&:company_type)
      grouped_options = company_by_type.keys.inject([]) do |grouping, company_type|
        companies = company_by_type[company_type]
        grouping << [company_type.humanize, companies.map{ |company| [company.name, company.id]}]
      end
      grouped_options_for_select grouped_options, selected
    )
  end

  def companies
    @companies ||= Company.order :name
  end
end

app/views/users/password_reset/new.html.erb
<div class="has-text-centered">
  <% if flash[:error] %>
    <div class="notification is-system is-danger">
      <%= flash[:error] %>
    </div>
  <% end %>

  <% if flash[:notice] %>
    <div class="notification is-system is-success">
      <%= flash[:notice] %>
    </div>
  <% end %>

  <% flash.clear %>
</div>
<div data-controller="password-reset">
  <div class="header">
    <div class="d-flex header-wrap">
      <span class="icon">
        <i class="fas fa-key"></i>
      </span>
      <h1 class="title is-inline-block">Reset Password</h1>
    </div>
  </div>
  <div>
    <%= form_with url: users_password_reset_path, local: true do |form| %>
      <div class="columns">
        <div class="column">
          <fieldset class="form-fieldset">
            <div class="form-table">
              <div class="form-row">
                <%= form.label :old_password %>
                <div class="form-field-content">
                  <%= form.password_field :old_password %>
                </div>
              </div>
              <div class="form-row">
                <%= form.label :new_password %>
                <div class="form-field-content">
                  <%= form.password_field :new_password %>
                </div>
              </div>
              <div class="form-row">
                <%= form.label :new_password_confirmation %>
                <div class="form-field-content">
                  <%= form.password_field :new_password_confirmation %>
                </div>
              </div>
              <div class="form-row">
                <div class="form-field-content has-text-right" style="background:none">
                  <button type="submit" class="button is-primary">
                    Reset
                  </button>
                </div>
              </div>
            </div>
          </fieldset>
        </div>
      </div>
    <% end %>
  </div>
</div>