config/routes.rb
# frozen_string_literal: true

require 'sidekiq/web'

Sidekiq::Web.use Rack::Auth::Basic do |username, password|
  # Protect against timing attacks:
  # - See https://codahale.com/a-lesson-in-timing-attacks/
  # - See https://thisdata.com/blog/timing-attacks-against-string-comparison/
  # - Use & (do not use &&) so that it doesn't short circuit.
  # - Use digests to stop length information leaking (see also ActiveSupport::SecurityUtils.variable_size_secure_compare)
  ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(username), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_USERNAME"])) &
    ActiveSupport::SecurityUtils.secure_compare(::Digest::SHA256.hexdigest(password), ::Digest::SHA256.hexdigest(ENV["SIDEKIQ_PASSWORD"]))
end if Rails.env.production?

Rails.application.routes.draw do
  post "/graphql", to: "graphql#execute"
  root 'sessions#new'

  get 'sessions/destroy'

  resources :sessions, only: [ :new, :create ]
  namespace :admin do
    resources :companies do
      resources :billing_details, only: [ :new, :create ], controller: 'companies/billing_details'
      resources :video_play_logs, only: [ :new, :create ], controller: 'companies/video_play_logs'
      resources :credits, only: [ :index, :new, :create ], controller: 'companies/credits'
      resources :channels, only: [ :index ], controller: 'companies/channels'
      resources :channel_playlists, only: [ :index ], controller: 'companies/channel_playlists'
    end
    resources :users
    resources :videos do
      member do
        post 'approve'
        post 'reject'
      end
    end
  end

  namespace :fleet do
    namespace :admin do
      resources :videos, only: [ :index ] do
        resources :approvals, only: [ :create ], controller: 'videos/approvals'
        resources :rejections, only: [ :create ], controller: 'videos/rejections'
      end
    end
    resources :channels, only: [ :index ]
    resources :channel_playlists, only: [ :index ]
    resources :channel_playlist_assignments
    resources :vessels
    resources :vessel_route_schedules, only: %i[ index create ] do
      collection do
        post 'new_schedule'
      end

      member do
        post 'activate'
        post 'deactivate'
      end
    end
    resources :vessel_routes, except: %i[destroy]
    resources :vessel_schedules, only: [ :index, :show ]
    resources :vessel_waypoints, only: [ :new ]
    resources :playlist_assignments, only: %i[ new create ]
    resources :playlists do
      member do
        post 'set_default'
      end
    end
    resources :onboarding_playlist, controller: 'playlists'
    resources :offboarding_playlist, controller: 'playlists'
    resources :videos
    resources :playlist_videos do
      member do
        post 'set_play_order'
      end
    end

    get 'vessel_media_settings/edit/:vessel_id/:route_id',
      to: 'vessel_media_settings#edit', as: :edit_vessel_media_settings

    post 'save/:id',
      to: 'vessel_media_settings#save', as: :save_vessel_media_settings
  end

  namespace :media do
    resources :campaigns do
      collection do
        post 'set_playlist'
      end
    end
    resources :playlists do
      member do
        post 'archive'
        post 'set_default'
      end
    end
    resources :spots do
      collection do
        post 'calculate'
      end
    end
    resources :videos
    resources :playlist_assignments
    resources :playlist_videos do
      member do
        post 'set_play_order'
      end
    end
  end

  namespace :content_provider do
    resources :videos
  end

  namespace :spots do
    resources :vehicle_route_schedules, only: [ ], controller: '/media/spots/vehicle_route_schedules' do
      collection do
        post 'search'
      end
    end
  end

  namespace :users do
    resource :password_reset, only: [ :new, :create ], controller: '/users/password_reset'
  end

  mount Sidekiq::Web => '/sidekiq'
  if Rails.env.development?
    mount GraphiQL::Rails::Engine, at: "/graphiql", graphql_path: "/graphql"
  end
end

app/views/shared/_modal.html.erb
<div id="modal-container"></div>

app/views/shared/_pager.html.erb
<footer>
  <%= will_paginate pager.results, page_links: false, renderer: Skooteo::WillPaginate::LinkRenderer,\
      params: (options ||= { }) %>
</footer>

app/views/shared/_save_notification.html.erb
<span class="save-notification is-italic is-bold" id="save_notification">
  Last saved at <%= record.updated_at.strftime("%B %d, %Y %A %I:%M:%S %p") %>
</span>

app/views/shared/_sidebar.html.erb
<div class="sidebar-header">
  <%= image_tag("/images/logo.png", :alt => "skooteo media") %>
</div>

<div class="profile">
  <div class="media">
    <div class="media-content">
      <div class="content">
        <p class="m-b-md m-t-sm">
          <strong><%= Current.person.full_name %></strong>
          <small class="d-block"><%= [Current.user.role.name, Current.company.name].join ' : '%></small>
        </p>
        <%= link_to new_users_password_reset_path do %>
          <span class="icon"><i class="fas fa-key"></i></span>
          <span>Reset Password</span>
        <% end %>
        <%= link_to sessions_destroy_path do %>
          <span class="icon"><i class="fas fa-sign-out-alt"></i></span>
          <span>Sign Out</span>
        <% end %>
      </div>
    </div>
  </div>
</div>
<% if Current.company.advertiser? %>
  <nav class="level">
    <div class="level-item has-text-centered" id="small-info">
        <div>
          <p class="heading">Campaigns</p>
          <p class="heading has-text-danger">
            <%= format_number(Current.company.campaigns.incoming.count) %>
          </p>
        </div>
      </div><div class="level-item has-text-centered">
        <div>
          <p class="heading">Spots</p>
          <p class="heading has-text-danger">
            <%= format_number(Current.company.campaigns.incoming.map(&:spots).flatten.sum(&:count)) %>
          </p>
        </div>
      </div><div class="level-item has-text-centered">
        <div>
          <p class="heading">Credits</p>
          <p class="heading">
            <strong class="has-text-link">
              <%= format_currency(Current.company.credits.sum(:amount)) %>
            </strong>
          </p>
        </div>
      </div>
  </nav>
<% end %>
<div class="menu-wrap" data-controller="sidebar">
  <ul class="sidebar-nav" data-role='["admin"]'>
    <li data-class="admin/companies">
      <%= link_to admin_companies_path(company_type: 'fleet_operator', format: 'html') do %>
        <span class="icon"><i class="far fa-building"></i></span>
        <span>Companies</span>
      <% end %>
    </li>
    <li data-class="admin/users">
      <%= link_to admin_users_path(format: 'html') do %>
        <span class="icon"><i class="fas fa-users"></i></span>
        <span>Users</span>
      <% end %>
    </li>
    <li data-class="admin/videos">
      <%= link_to admin_videos_path(format: 'html') do %>
        <span class="icon"><i class="far fa-thumbs-up"></i></span>
        <span>Videos</span>
      <% end %>
    </li>
  </ul>

  <ul class="sidebar-nav" data-role='["fleet_operator", "fleet_operator_admin"]'>
    <li data-class="fleet/vessels">
      <%= link_to fleet_vessels_url do %>
        <span class="icon"><i class="fas fa-ship"></i></span>
        <span>Vessels</span>
      <% end %>
    </li>
    <li data-class="fleet/vessel_schedules">
      <%= link_to fleet_vessel_schedules_path do %>
        <span class="icon"><i class="far fa-calendar-alt"></i></span>
        <span>Schedules</span>
      <% end %>
    </li>
  </ul>

  <ul class="sidebar-nav" data-role='["fleet_operator_admin"]'>
    <li data-class="fleet/playlists">
      <%= link_to fleet_playlists_path do %>
        <span class="icon"><i class="fas fa-bullhorn"></i></span>
        <span>Announcements</span>
      <% end %>
    </li>

    <% if Current.company.addons.enabled?(Addon.available.media) %>
      <li data-class="fleet/channels">
        <%= link_to fleet_channels_path do %>
          <span class="icon"><i class="fas fa-play-circle"></i></span>
          <span>Entertainment</span>
        <% end %>
      </li>
      <li data-class="fleet/admin/videos">
        <%= link_to fleet_admin_videos_path(format: 'html') do %>
          <span class="icon"><i class="fas fa-play"></i></span>
          <span>Media</span>
        <% end %>
      </li>
    <% end %>

  </ul>

  <ul class="sidebar-nav" data-role='["content_provider"]'>
    <li data-class="content_provider/videos">
      <%= link_to content_provider_videos_path do %>
        <span class="icon"><i class="fas fa-play"></i></span>
        <span>Media</span>
      <% end %>
    </li>
  </ul>

  <ul class="sidebar-nav" data-role='["advertiser"]'>
    <li data-class="media/spots">
      <%= link_to media_spots_path do %>
        <span class="icon"><i class="fas fa-table"></i></span>
        <span>Spots</span>
      <% end %>
    </li>
    <li data-class="media/campaigns">
      <%= link_to media_campaigns_path do %>
        <span class="icon"><i class="fas fa-file-video"></i></span>
        <span>Campaigns</span>
        <% unless Current.company.campaigns.incoming.empty? %>
          <span class="badge"><%= format_number(Current.company.campaigns.incoming.count) %></span>
        <% end %>
      <% end %>
    </li>
    <li data-class="media/playlists">
      <%= link_to media_playlists_path do %>
        <span class="icon"><i class="fas fa-file-video"></i></span>
        <span>Videos</span>
      <% end %>
    </li>
  </ul>
</div>